In [ ]:

number = int(input("Please Enter any Number: "))

last_digit1 = number % 10

print("The Last Digit in a Given Number %d = %d" %(number, last_digit1))


num1= int(input("Please Enter any Number: "))

last_digit2 = num1 % 10

print("The Last Digit in a Given Number %d = %d" %(num1, last_digit2))

num2 = int(input("Please Enter any Number: "))

last_digit3 = num2 % 10

print("The Last Digit in a Given Number %d = %d" %(num2, last_digit3))

print()
if last_digit1 * last_digit2 == last_digit3:
     print("True")
else:
    print("false")


Please Enter any Number: 23
The Last Digit in a Given Number 23 = 3
Please Enter any Number: 23
The Last Digit in a Given Number 23 = 3
Please Enter any Number: 23
The Last Digit in a Given Number 23 = 3

false


In [ ]:
rating=4

if rating>4:
    print('Great movie')
elif rating>2:
    print('Good movie')
else:
    print('Bad movie')

Good movie


In [ ]:
#Correct the code
stars = 3

print(stars)

if stars == 2:
  print("Outcome is 2.")
elif stars == 5:
  print("Outcome is 3.")
elif stars == 3:
  print("Outcome is 5.")
else:
  print("Outcome is not present.")

3
Outcome is 5.


In [ ]:
num = input('Enter a number between 3 and 9: ')
num = int(num)
while num < 3 or num > 9:
  print("Invalid Input")
  player_input = input("Please enter a number between 3 and 9: ")
  num = int(player_input)

Enter a number between 3 and 9: 3


In [ ]:
global a

a=2

def func():
    a=1
    b=2
    return (a+b)

print(func())

3


In [ ]:

if num % 3 == 0:
   print("The number is divisible by 3")
else:
   print("The number is not divisible by 3")


div(9)

The number is divisible by 3


NameError: ignored

In [ ]:
c = 1 # global variable

def add():
  c = c + 2 # increment c by 2
  print(c)

add()

UnboundLocalError: ignored

In [ ]:
x = False

print(not x)

True


In [ ]:
factor = 1
while factor > 0:
  factor = factor * 5
  if factor == 5 ** 5:
    break
print(factor)

3125


In [ ]:
my_list = []
num = 10
while num > 2:
  if num % 3 == 0:
    my_list.append(num)
  num = num - 1

my_list

[9, 6, 3]

In [ ]:
factors=[]
num=1
# while loop
while num<=100:
    if (num % 10 == 0):
        factors.append(num)
    num+=1
print(factors)

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]


In [ ]:
Mylist = [ "a", "a", "b", "b", "b", "c", "c", "d", "e"]
Mylist.index("b")


2

In [ ]:
print(Mylist)

['a', 'a', 'b', 'b', 'b', 'c', 'c', 'd', 'e']


In [ ]:
#Creating Sub list

product = ['Pencil', 'Pen', 'Pencil Box', 'Scale']
price= [5, 10, 2, 20, 12]
brand = ['Camlin', 'Rotomac', 'Camlin', 'Apsara']

#Creating a 2D list

stationery = [product, price, brand]

#find the missing value in the 2D list

for i in range(len(stationery)):
  for j in range(len(stationery[i])):
    print("Item at row ",i ,"column", j , "is", stationery[i][j] )

Item at row  0 column 0 is Pencil
Item at row  0 column 1 is Pen
Item at row  0 column 2 is Pencil Box
Item at row  0 column 3 is Scale
Item at row  1 column 0 is 5
Item at row  1 column 1 is 10
Item at row  1 column 2 is 2
Item at row  1 column 3 is 20
Item at row  1 column 4 is 12
Item at row  2 column 0 is Camlin
Item at row  2 column 1 is Rotomac
Item at row  2 column 2 is Camlin
Item at row  2 column 3 is Apsara


In [ ]:
three_d_list = [ [ [1, 1, 1], [2, 2, 2], [3, 3, 3] ],
                [[4, 4, 4], [5, 5, 5], [6, 6, 6]] ]
len(three_d_list)

2

In [ ]:
my_list = [1,2,3,4,5]
k = [print(i) for i in my_list if i != 6]
print(k)

1
2
3
4
5
[None, None, None, None, None]


In [ ]:
ones = [[[5 for i in range(2)] for j in range(4)] for k in range(3)]
ones

[[[5, 5], [5, 5], [5, 5], [5, 5]],
 [[5, 5], [5, 5], [5, 5], [5, 5]],
 [[5, 5], [5, 5], [5, 5], [5, 5]]]

In [ ]:
print([[i+j for i in range(4)] for j in range(2)])

[[0, 1, 2, 3], [1, 2, 3, 4]]


In [ ]:
two_dim = [[(10 * i + j) for j in range(1, 3)] for i in range(1, 3)]
two_dim


[[11, 12], [21, 22]]

In [ ]:
# Execute your code here
import numpy as np

#Generate five random numbers from the range 1 - 10 in an array 'a'
a = np.random.randint(1,10,5)

square_root = np.sqrt(a)

for i in range(len(a)):
  print("The square root of ",a[i], "is", square_root[i])

The square root of  3 is 1.7320508075688772
The square root of  2 is 1.4142135623730951
The square root of  6 is 2.449489742783178
The square root of  7 is 2.6457513110645907
The square root of  7 is 2.6457513110645907


In [ ]:
# Write your code here
# Step 1: Import numpy module
import numpy as np
# Step 2: Declare a variable 'x' to store the result and use 'linspace()' and 'reshape()' functions
x = np.linspace(12, 21,4, dtype=int).reshape(2,2)
# Step 3: Print the variable 'x' to see the output
print(x)

[[12 15]
 [18 21]]


In [ ]:
import numpy as np

width_of_square = [i for i in range(1,50,5)]

#Code to convert a list into an array because mathematical operations cannot be performed on list
width_of_square = np.array(width_of_square)

area_of_square = width_of_square ** 2

print(width_of_square, area_of_square)

[ 1  6 11 16 21 26 31 36 41 46] [   1   36  121  256  441  676  961 1296 1681 2116]


In [ ]:
import numpy as np

a = np.array([1,2,3,5,8])
b = np.array([0,3,4,2,1])
c = a + b
c = c*a

print (c[2])

21


In [ ]:
# Create a 3D NumPy array of size (2, 2, 2) whose all the elements are 0.
import numpy as np

inputs = np.zeros(shape=(2, 2, 2), dtype=int)
inputs

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [ ]:
# Code to find the size of two dimensional array:
import numpy as np
two_dim_ar = np.arange(1, 19).reshape(3, 6)
print("Number of items in two_dim_ar:", two_dim_ar.size)

Number of items in two_dim_ar: 18


In [ ]:
import numpy as np
prices = np.array([13999, 6298, 10999, 14999, 7298])
units_available = np.array([9, 8, 9, 9, 8])

# Write your code here
total_price_for_each_bicycle = prices * units_available
print(total_price_for_each_bicycle)

# Calculate the total monetary value.
total_monetary_value = np.sum(total_price_for_each_bicycle)
total_monetary_value

[125991  50384  98991 134991  58384]


468741

In [ ]:
# 1. Import the 'numpy', 'pandas' and 'time' modules
import numpy as np
import pandas as pd
import time

# 2. Record the time before creating a Pandas Series.
py_t0 = time.time()

# 3. Create a Python list containing 100,000 items from 1 to 100,000.
py_series = pd.Series([i for i in range(1, 100001)])

# 4. Record the time after creating the list.
py_t1 = time.time()

# 5. Calculate the time taken to create a Python list by computing the time difference.
py_time_diff = (py_t1 - py_t0)
print("Time taken to create a Pandas series is", py_time_diff, "seconds.")

# 6. Record the time before creating a NumPy array.
np_t0 = time.time()

# 7. Create a NumPy array containing just one row and 100,000 items from 1 to 100,000.
np_ones = np.arange(1, 100001)

# 8. Record the time after creating the NumPy array.
np_t1 = time.time()

# 9. Calculate the time taken to create a NumPy array by computing the time difference.
np_time_diff = (np_t1 - np_t0)
print("Time taken to create a NumPy array is", np_time_diff, "seconds.")

# 10. Calculate the factor by which a NumPy array creation is faster than a Python list creation.
print("A NumPy array is", py_time_diff // np_time_diff, "times faster than a Pandas Series for the same size.")
# Recall that // means floor division.

Time taken to create a Pandas series is 0.034136295318603516 seconds.
Time taken to create a NumPy array is 0.0002512931823730469 seconds.
A NumPy array is 135.0 times faster than a Pandas Series for the same size.


In [ ]:
import pandas as pd
index = pd.Series([1, 3, 2, 2, 1,2,1,2,3,4])
index.value_counts()

2    4
1    3
3    2
4    1
dtype: int64

In [ ]:
# Solution
import pandas as pd
import random
def compute_median(num_series):
  result = 0
  num_list = [num for num in num_series]
  num_list.sort()
  if len(num_list) % 2 == 0:
    result = (num_list[(len(num_list) // 2) - 1] + num_list[len(num_list) // 2]) / 2
  else:
    result = float(num_list[len(num_list) // 2])
  return result

num_series = pd.Series([random.randint(20, 40) for i in range(9)])
print("Median without using the standard median() function:", compute_median(num_series))
print("Median using the standard median() function:", num_series.median())

Median without using the standard median() function: 29.0
Median using the standard median() function: 29.0


In [ ]:
import numpy as np
import pandas as pd

sal_df = pd.read_csv('https://raw.githubusercontent.com/CoreyMSchafer/code_snippets/master/Python/Matplotlib/10-Subplots/data.csv')
sal_df.head()

,Age,All_Devs,Python,JavaScript
0,18,17784,20046,16446
1,19,16500,17100,16791
2,20,18012,20000,18942
3,21,20628,24744,21780
4,22,25206,30500,25704


In [ ]:
# Complete the code to find total number of missing values
num_missing_values = 0

for column in sal_df.columns:
  for item in sal_df[column].isnull():
    if item == True:
      num_missing_values += 1


num_missing_values

0

In [ ]:
my_series_13 = sal_df.iloc[13, :]
my_series_13

Age              31
All_Devs      62316
Python        70003
JavaScript    62375
Name: 13, dtype: int64

In [ ]:
# Solution
def time_saved(s_lim, s_avg, d):
    norm_time = (d / s_lim) * 60
    fast_time = (d / s_avg) * 60
    worth = norm_time - fast_time
    return worth
time_saved(80, 90, 4000)

333.3333333333335

In [ ]:
# Python script for confusion matrix creation.
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

actual = [1, 1, 0, 1, 0, 0, 1, 0, 0, 0]
predicted = [1, 0, 0, 1, 0, 0, 1, 1, 1, 0]
results = confusion_matrix(actual, predicted)

print('Confusion Matrix :')
print(results)

Confusion Matrix :
[[4 2]
 [1 3]]


In [ ]:
# Create a function to normalise a Pandas series using the mean normalisation method.
import pandas as pd
def mean_normalise(series):
  norm_series = (series - series.mean()) / (series.max() - series.min())
  return norm_series

test_series = pd.Series([7, 11, 2000, 119, 540])
mean_normalise(test_series)

In [ ]:
# code to print the transpose of matrix
import numpy as np
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
print("\n")
print(matrix.T)